### ISSUE TITLE
Error publishing to crates

### ISSUE THREAD

**Issue by gmlarumbe** [tree-sitter/workflows#33]
Hi,

I came across an error while trying to publish the https://github.com/gmlarumbe/tree-sitter-systemverilog grammar to npm, PyPI and crates using this repo workflows.

npm and PyPI worked well but crates gives the following error on the "Publish to crates.io" step: 
```
Run cargo publish
    Updating crates.io index
error: 60 files in the working directory contain changes that were not yet committed into git:
node_modules/@isaacs/fs-minipass/LICENSE
node_modules/@npmcli/fs/lib/cp/LICENSE
node_modules/abbrev/LICENSE
node_modules/agent-base/LICENSE
node_modules/brace-expansion/LICENSE
node_modules/color-convert/LICENSE
node_modules/color-name/LICENSE
node_modules/cross-spawn/LICENSE
node_modules/cross-spawn/node_modules/isexe/LICENSE
node_modules/cross-spawn/node_modules/which/LICENSE
node_modules/debug/LICENSE
node_modules/exponential-backoff/LICENSE
node_modules/fdir/LICENSE
node_modules/foreground-child/LICENSE
node_modules/fs-minipass/LICENSE
node_modules/glob/LICENSE
node_modules/graceful-fs/LICENSE
node_modules/http-cache-semantics/LICENSE
node_modules/http-proxy-agent/LICENSE
node_modules/https-proxy-agent/LICENSE
node_modules/ip-address/LICENSE
node_modules/isexe/LICENSE
node_modules/jsbn/LICENSE
node_modules/lru-cache/LICENSE
node_modules/make-fetch-happen/LICENSE
node_modules/minimatch/LICENSE
node_modules/minipass-collect/LICENSE
node_modules/minipass-fetch/LICENSE
node_modules/minipass-flush/LICENSE
node_modules/minipass-flush/node_modules/minipass/LICENSE
node_modules/minipass-flush/node_modules/yallist/LICENSE
node_modules/minipass-pipeline/LICENSE
node_modules/minipass-pipeline/node_modules/minipass/LICENSE
node_modules/minipass-pipeline/node_modules/yallist/LICENSE
node_modules/minipass-sized/LICENSE
node_modules/minipass-sized/node_modules/minipass/LICENSE
node_modules/minipass-sized/node_modules/yallist/LICENSE
node_modules/minipass/LICENSE
node_modules/minizlib/LICENSE
node_modules/mkdirp/LICENSE
node_modules/negotiator/LICENSE
node_modules/node-gyp-build/LICENSE
node_modules/node-gyp/LICENSE
node_modules/node-gyp/gyp/LICENSE
node_modules/node-gyp/gyp/pylib/packaging/LICENSE
node_modules/nopt/LICENSE
node_modules/picomatch/LICENSE
node_modules/proc-log/LICENSE
node_modules/promise-retry/LICENSE
node_modules/semver/LICENSE
node_modules/smart-buffer/LICENSE
node_modules/socks-proxy-agent/LICENSE
node_modules/socks/LICENSE
node_modules/sprintf-js/LICENSE
node_modules/tar/LICENSE
node_modules/tinyglobby/LICENSE
node_modules/unique-filename/LICENSE
node_modules/unique-slug/LICENSE
node_modules/which/LICENSE
src/parser.c
to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
Error: Process completed with exit code 101.
```

This is my `publish.yml` file:
```yaml
name: Publish packages

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
      attestations: true
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    with:
      generate: true
  crates:
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
    with:
      generate: true
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      generate: true
```

I believe I have set all the registries tokens properly.

On the other hand .gitignore seems to ignore Node artifacts (i.e. node_modules/ directory):
```gitignore
# Node artifacts
build/
prebuilds/
node_modules/
```

Am I missing something?

Thanks a lot!
